# If set to true, will check for updates
Check-For-Updates: true

# List of the enabled categories.
Categories-Enabled:
  Gadgets: true
  Particle-Effects: true
  Mounts: true
  Pets: true
  Morphs: true
  Hats: true
  Suits: true
  Emotes: true
  Projectile-Effects: true
  Death-Effects: true

# Other settings for categories:
# - The Item in Main Menu.
# - Do you want a BackToMainMenu Arrow in it?
Categories:
  Gadgets:
    Main-Menu-Item: IRON_AXE
    Go-Back-Arrow: true
    # You wanna show the cooldown of current gadget in actionbar?
    Cooldown-In-ActionBar: true
    # Whether a player can disable gadgets for themself using `/uc gadgets` or the menu button.
    # When gadgets are disabled for a player, they cannot use gadgets or be affected by others' gadgets.
    # When set to false, gadgets are always per-player enabled for all players.
    # Disabling the gadgets category entirely will work regardless of this setting.
    Allow-Disable-Gadgets: true
  Particle-Effects:
    Main-Menu-Item: BLAZE_POWDER
    Go-Back-Arrow: true
  Mounts:
    Main-Menu-Item: SADDLE
    Go-Back-Arrow: true
  Pets:
    Main-Menu-Item: BONE
    Go-Back-Arrow: true
  Morphs:
    Main-Menu-Item: LEATHER
    Go-Back-Arrow: true
  Hats:
    Main-Menu-Item: GOLDEN_HELMET
    Go-Back-Arrow: true
  Suits:
    Main-Menu-Item: LEATHER_CHESTPLATE
    Go-Back-Arrow: true
  Emotes:
    Go-Back-Arrow: true
  Projectile-Effects:
    Main-Menu-Item: ARROW
    Go-Back-Arrow: true
  Death-Effects:
    Main-Menu-Item: WITHER_SKELETON_SKULL
    Go-Back-Arrow: true
  Clear-Cosmetic-Item: BARRIER
  Previous-Page-Item: ENDER_PEARL
  Next-Page-Item: EYE_OF_ENDER
  Back-Main-Menu-Item: ARROW
  Self-View-Item:
    # Item in Morphs Menu when Self View enabled.
    When-Enabled: ENDER_EYE
    # Item in Morphs Menu when Self View disabled.
    When-Disabled: ENDER_PEARL
  Gadgets-Item:
    # Item in Gadgets Menu when Gadgets enabled.
    When-Enabled: LIGHT_GRAY_DYE
    # Item in Gadgets Menu when Gadgets disabled.
    When-Disabled: GRAY_DYE
  # Item in Pets Menu to rename current pet.
  Rename-Pet-Item: NAME_TAG
  # Should GUI close after selecting a cosmetic?
  Close-GUI-After-Select: true
  Back-To-Main-Menu-Custom-Command:
    Enabled: false
    Command: cc open custommenu.yml {player}

# The economy that should be used. Supports 'Vault', 'PlayerPoints', 'Treasury', 'PEconomy', or 'CoinsEngine'.
Economy: 'Vault'

# If the economy above supports multiple currencies, you can pick a specific currency here.
# If this is not set and the economy has no default currency, UC may pick a random one.
Economy-Currency: ''

# Describes how UC should interact with plugins through the Vault API with regard to
# a player's minimum balance. Available options are:
# - 'delegate': UC will let the economy plugin decide whether a player has enough money to make a purchase.
#     Your economy plugin should do this, so USE 'delegate' UNLESS you're experiencing an issue.
#
# - 'nonnegative': UC will assume that players must have a non-negative balance to make a purchase,
#     but will still check whether the economy plugin returned a success.
#     You may need this if your economy plugin runs async and doesn't immediately
#     know whether a transaction can be performed.
#
# - 'force-nonnegative': UC will assume that players must have a non-negative balance to make a purchase,
#     and will assume success regardless of what the economy plugin returns.
#     You should ONLY use this if your economy plugin responds improperly to UC's requests,
#     for example returning null instead of a response.
Vault-Balance-Validation: 'delegate'

# Treasure Chests Settings.
#
# NOTE: If money loot is enabled, it will be given when no cosmetics are available, regardless of its chance.
# This means that if you want to give money ONLY when no cosmetics are available, just set the chance to 0
# instead of disabling it!
#
# About Treasure Chests designs:
# For a list of effect: http://pastebin.com/CVKkufck
# For the chest-types: NORMAL or ENDER
# Material syntax: The "item ID" from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# You CAN make more designs just copy one, paste it and modify.
# Not twice same name!
#
# Some infos:
# center-block: The block on the center.
# around-center: Blocks around the center
# third-BLOCKS: BLOCKS "around around" the center.
# below-chests: Block below the chests.
# barriers: the barrier.
# chest-type: The chest type (NORMAL or ENDER)
# effect: The effect (complete list: http://pastebin.com/CVKkufck)
#
TreasureChests:
  Enabled: true
  Key-Price: 1000
  # How many treasure chests should be opened per key? Min 1, max 4
  Count: 4
  # If true, treasure chests will occupy a 7x7 area instead of 5x5,
  # and you can have up to 12 treasure chests per key.
  Large: false
  # Whether players opening chests can be damaged
  Allow-Damage: false
  # The treasure chest mode. Options:
  # - structure: places blocks and chests (default)
  # - simple: only gives <Count> cosmetics, no blocks are placed
  # - both: players can choose either mode through the GUI
  Mode: structure
  Locations:
    # Whether players should be moved to a certain
    # location before opening a treasure chest.
    # Does not override /uc treasure with position args.
    Enabled: false
    default:
      # The location players should be moved to.
      # Block coordinates only, like 104, not 103.63
      X: 0
      Y: 63
      Z: 0
      World: world
  Loots:
    Money:
      Enabled: true
      Min: 15
      Max: 100
      Chance: 10
      Message:
        enabled: false
    Gadgets-Ammo:
      Enabled: true
      Min: 20
      Max: 100
      Chance: 60
      Message:
        enabled: false
    Gadgets:
      Enabled: true
      Chance: 20
      Message:
        enabled: false
    Mounts:
      Enabled: true
      Chance: 10
      Message:
        enabled: false
    Pets:
      Enabled: true
      Chance: 10
      Message:
        enabled: false
    Morphs:
      Enabled: true
      Chance: 4
      Message:
        enabled: true
    Particle-Effects:
      Enabled: true
      Chance: 4
      Message:
        enabled: true
    Hats:
      Enabled: true
      Chance: 10
      Message:
        enabled: false
    Suits:
      Enabled: true
      Chance: 5
      Message:
        enabled: false
    Emotes:
      Enabled: true
      Chance: 5
      Message:
        enabled: false
    Projectile-Effects:
      Enabled: true
      Chance: 5
      Message:
        enabled: false
    Death-Effects:
      Enabled: true
      Chance: 5
      Message:
        enabled: false
    Commands:
      # Overall chance of any command being selected as a reward.
      # If greater than 0, commands will be entered into the randomizer as a whole
      # using this chance, and the weights defined in each command will only choose between other commands.
      # Otherwise, (default) each command will be entered into the randomizer directly,
      # each with its own defined weight.
      Overall-Chance: 0
      shoutout:
        Name: '<bold><purple>Shoutout'
        Material: NETHER_STAR
        Enabled: false
        Chance: 100
        Message:
          enabled: false
        Cancel-If-Permission: 'no'
        Commands:
          - 'say %name% is awesome!'
      flower:
        Name: '<bold><yellow>Flower'
        Material: YELLOW_FLOWER
        Enabled: false
        Chance: 100
        Message:
          enabled: false
        Cancel-If-Permission: 'example.yellowflower'
        Commands:
          - 'give %name% yellow_flower 1'
          - 'lp user %name% permission set example.yellowflower true'
  Designs:
    Classic:
      center-block: SEA_LANTERN
      around-center: OAK_PLANKS
      third-blocks: SPRUCE_PLANKS
      below-chests: OAK_LOG
      barriers: OAK_FENCE
      chest-type: NORMAL
      effect: FLAME
    Modern:
      center-block: SEA_LANTERN
      around-center: BLUE_TERRACOTTA
      third-blocks: WHITE_TERRACOTTA
      below-chests: BLUE_TERRACOTTA
      barriers: LIGHT_BLUE_STAINED_GLASS_PANE
      chest-type: ENDER
      effect: REDSTONE
    Nether:
      center-block: GLOWSTONE
      around-center: SOUL_SAND
      third-blocks: NETHERRACK
      below-chests: NETHER_BRICKS
      barriers: NETHER_BRICK_FENCE
      chest-type: NORMAL
      effect: SMOKE_NORMAL
    End:
      center-block: GLOWSTONE
      around-center: END_STONE
      third-blocks: END_STONE
      below-chests: END_STONE
      barriers: END_PORTAL_FRAME
      chest-type: ENDER
      effect: PORTAL
    Winter:
      center-block: GLOWSTONE
      around-center: SNOW_BLOCK
      third-blocks: PACKED_ICE
      below-chests: SNOW_BLOCK
      barriers: SPRUCE_FENCE
      chest-type: NORMAL
      effect: SNOWBALL
    Jungle:
      center-block: GLOWSTONE
      around-center: GRASS_BLOCK
      third-blocks: JUNGLE_LOG
      below-chests: MOSSY_COBBLESTONE
      barriers: JUNGLE_LEAVES
      chest-type: NORMAL
      effect: VILLAGER_HAPPY
    Ocean:
      center-block: SEA_LANTERN
      around-center: PRISMARINE_BRICKS
      third-blocks: DARK_PRISMARINE
      below-chests: PRISMARINE
      barriers: BLUE_STAINED_GLASS_PANE
      chest-type: ENDER
      effect: DRIP_WATER
    Halloween:
      center-block: JACK_O_LANTERN
      around-center: MYCELIUM
      third-blocks: PODZOL
      below-chests: MOSSY_COBBLESTONE
      barriers: MOSSY_COBBLESTONE_WALL
      chest-type: ENDER
      effect: SPELL_WITCH
  # This should be set to a command that sets permissions so UC can give cosmetics from treasure chests.
  # %name% will be replaced with the player's name, and %permission% will be replaced with the permission to add.
  #
  # Alternatively, if you're using LuckPerms, you can use '!lp-api' to access the LuckPerms API directly rather than using commands.
  # If you want to apply LuckPerms contexts to the added permissions, simply add them after !lp-api, like: '!lp-api server=hub'
  # Adding nolog will suppress logging of added permissions
  #
  # [BETA] Set to '' to store unlocked cosmetics in data files or SQL
  Permission-Add-Command: ''

# This option will fill the blank slots of inventories
# with a custom item!
Fill-Blank-Slots-With-Item:
  Enabled: false
  Item: LIGHT_GRAY_STAINED_GLASS_PANE

# List of commands that won't work when cosmetics are equipped.
# Command arguments are ignored, commands are blocked when base command matches.
Disabled-Commands:
  - hat

# List of the worlds where cosmetics are enabled!
# If list contains '*', all worlds will be allowed.
Enabled-Worlds:
  - '*'

# Toggle this to allow players to rename pets.
#
# Permission-Required:
# If true, the permission:
# ultracosmetics.pets.rename
# will be required to rename a pet.
#
# Requires Money:
# If true, money will be required
# to rename a pet.
Pets-Rename:
  Enabled: false
  Permission-Required: false
  Requires-Money:
    Enabled: true
    Price: 100

# Do pets drop items? (not pickable up by players)
Pets-Drop-Items: true

# Are pets babies?
Pets-Are-Babies: true

# Are pets prevented from making sounds?
Pets-Are-Silent: false

# Show names over pets' heads?
Show-Pets-Names: true

# Are gadgets prevented from making sounds?
Gadgets-Are-Silent: false

# Do you want the mounts
# that normally make block trails
# to do so?
Mounts-Block-Trails: true

# Should players on UC mounts be able to be damaged?
allow-damage-to-players-on-mounts: false

# Adds extra attributes to specified categories. 1.13+ only
# See the wiki page for details: https://github.com/datatags/UltraCosmetics/wiki/Attribute-Bonuses
# Full list of attributes:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html
# Only supported on 1.9.4+
Attribute-Bonus:
  EMOTES:
    GENERIC_ARMOR: 2
  HATS:
    GENERIC_ARMOR: 2
  SUITS_HELMET:
  SUITS_CHESTPLATE:
  SUITS_LEGGINGS:
  SUITS_BOOTS:

# This option allows to use ammo
# for gadgets, for limited uses.
# Ammo can be given with /uc give ammo
# or bought from menu when activating gadget.
Ammo-System-For-Gadgets:
  Enabled: false
  # Do you want it so each gadget item in the menu has an amount corresponding to your ammo?
  Show-Ammo-In-Menu-As-Item-Amount: true
  # Whether players should be allowed to purchase ammo
  Allow-Purchase: true

MySQL:
  Enabled: false
  hostname: localhost
  username: root
  password: password
  port: '3306'
  # Database must already exist, tables will be created
  database: UltraCosmetics
  # Stores player UUID and settings
  player-data-table: UltraCosmetics-PlayerData
  cosmetics-table: UltraCosmetics-Cosmetics
  ammo-table: UltraCosmetics-Ammo
  pet-names-table: UltraCosmetics-PetNames
  equipped-cosmetics-table: UltraCosmetics-EquippedCosmetics
  unlocked-cosmetics-table: UltraCosmetics-UnlockedCosmetics

# The menu item settings.
#
# List for type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
Menu-Item:
  Enabled: false
  Slot: 3
  Type: ENDER_CHEST
  Displayname: '<bold><gold>Cosmetics'
  # Lore to apply to the menu item. Set to '' to disable
  Lore: |-
    <green>Right-click with this
    <green>to open the menu
  # Custom model data for the menu item. Only supported on MC >= 1.14.4 (when it was added)
  Custom-Model-Data: 0
  # Whether to open cosmetics menu when the menu item is clicked from the player's inventory
  Open-Menu-On-Inventory-Click: false

# Settings related to permissions.
#
# List for type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
No-Permission:
  Show-In-Lore: true
  Dont-Show-Item: false
  Allow-Purchase: false
  Custom-Item:
    enabled: false
    Type: BARRIER
    Name: '<red><bold><cosmetic>'
    Lore: '\n<red><bold>You do not have permission for this!\n'

# If set to true, in messages the cosmetics' names
# won't be colored.
# Example:
# With true: &a&lYou activated &9&lPaintball Gun!
# With false: &a&lYou activated Paintball Gun!
Chat-Cosmetic-PlaceHolder-Color: true

# What is the slot for gadgets?
Gadget-Slot: 4

# If toggled to true,
# players will be able to remove
# their current gadget by pressing
# their drop key.
Remove-Gadget-With-Drop: false

# Allows for players to auto-equip on join cosmetics they had before disconnecting.
# Supports both flatfile and SQL, choosing SQL when possible.
Auto-Equip-Cosmetics: true

# When enabled, prints why area checks failed to the console
Area-Debug: false

# Materials that are treated as air. Changing these is not recommended.
Air-Materials:
  - AIR
  - CAVE_AIR
  - VOID_AIR
  - LIGHT

# Whether UltraCosmetics should automatically download and install new versions.
# Requires Check-For-Updates to be enabled.
Auto-Update: false

# Whether UltraCosmetics should prevent vanished players from using cosmetics.
# Works with any vanish plugin that uses 'vanished' metdata.
Prevent-Cosmetics-In-Vanish: false

# Limits the number of entities that can be spawned by a single gadget per tick (default 10.)
# Set to 0 to spawn all entities instantly.
Max-Entity-Spawns-Per-Tick: 10

# Languages supported by this version of UltraCosmetics.
# This is not a configurable list, just informative.
Supported-Languages: [ ]

# The language to use. Can be set to any language listed above.
Language: en

# Whether WorldGuard should be hooked when loading UC
# Disable this if UC has trouble loading WorldGuard.
# The server must be restarted to apply changes to this option.
WorldGuard-Integration: true

# Discord channel ID to send treasure chest loot messages to.
# Requires DiscordSRV. 0 to disable.
DiscordSRV-Loot-Channel: 0

# Whether NMS should be loaded. Options are:
# - auto: Try to load NMS, print an error if failed. (default)
# - no: Do not attempt to load NMS, only run without it.
#           Recommended if you want to try UC on a non-Spigot-based server.
# - force: Override minor version checking and try to load NMS,
#              even if it doesn't look like it's going to work.
Use-NMS: auto

# Entity types that are considered "projectiles" for the purposes of projectile effects.
# Valid options are found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# This only works for things that are Projectiles and are directly launched by the player (i.e. with a bow.)
# For hints on what a Projectile is, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Projectile.html
Projectile-Types:
  - ARROW
  - SNOWBALL
  - SPECTRAL_ARROW
  - TRIDENT

# If ChestSort is detected, hooks it to prevent moving the menu item.
# If ChestSort is not installed, this has no effect.
ChestSort-Hook: true

# If Towny is installed, UltraCosmetics will prevent Towny from removing UC's pets and mounts.
# If Towny is not installed, this has no effect.
Towny-Hook: true

# If PlayerAuctions is installed, prevents UC items from being sold.
PlayerAuctions-Hook: true

# The description style to use in the menus. Use MiniMessage formatting:
# https://docs.advntr.dev/minimessage/format.html#minimessage-format
Description-Style: "<gray><italic>"

# Whether running `/uc` by itself should open the main menu instead of displaying the help message.
Open-Menu-On-Base-Command: false

# Permission groups that are given discounts.
# For example, the group 'vip' will have the permission 'ultracosmetics.discount.vip'
# The discount is applied by multiplying the price by the discount value, so 0.8 is 20% off.
# The final amount will be rounded down, so if the normal price is $5, a 50% discount will make it $2.
Discount-Groups:
  vip: 0.8

# Whether non-player entities (e.g. animals) should be affected by cosmetics, such as gadgets.
Cosmetics-Affect-Entities: true

# Delay in ticks before UC should give items when the player joins, or respawns or changes worlds.
# 1 is enough for compatibility with most plugins, but if you're experiencing issues,
# consider increasing it to 5.
Item-Delay:
  Join: 1
  World-Change-Or-Respawn: 0

# Whether UC should always unequip/reequip cosmetics when changing worlds.
# Enable this if you use MV-Inventories or a similar plugin.
Always-Update-Cosmetics-On-World-Change: false
